# Generated by Django 4.2.19 on 2025-03-14 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_remove_user_name_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedsongs',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='storedsongs',
            name='notes',
        ),
        migrations.AddField(
            model_name='storedsongs',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='music_sheets/'),
        ),
        migrations.AlterField(
            model_name='storedsongs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
