# Generated by Django 4.2.19 on 2025-03-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_alter_storedsongs_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedsongs',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='music_sheets/'),
        ),
    ]
