# Generated by Django 4.2.19 on 2025-03-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_alter_storedsongs_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedsongs',
            name='pdfFile',
        ),
        migrations.AddField(
            model_name='storedsongs',
            name='pdfData',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
