# Generated by Django 4.2.19 on 2025-03-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_remove_storedsongs_pdffile_storedsongs_pdfdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedsongs',
            old_name='pdfData',
            new_name='pdfFile',
        ),
    ]
